### ISSUE TITLE
Download window enhancement 

### ISSUE THREAD

**Issue by gmkmario** [andreasgrafen/cascade#7] opened 2021-09-20 11:52 UTC
![Captura](https://user-images.githubusercontent.com/85378027/133997392-57cc5369-8061-4888-9c8f-00454bda1222.PNG)
The color is so dark that you can barely see the text.

**Comment by andreasgrafen** [comment] 2021-09-20 12:48
mmh, yeah. That's not good. I'll try to look into this but I don't have a windows machine to test the code on, which makes things a little bit more complicated.

I'd assume that you're already running the code with the latest changes? A lot of text-colour issues should have been removed by that, but it might very well be that this isn't affected.
Also: Is your browser itself set to a light or dark theme in the settings; and which theme variant are you using for your system overall?

**Comment by gmkmario** [comment] 2021-09-20 13:00
Using the latest version and the dark theme for system and browser.

**Comment by andreasgrafen** [comment] 2021-09-28 19:18
Nyeh! I can't even properly reproduce the problem which makes it even harder to fix.
I'll keep this issue open in case someone comes along and is willing to work on this. I'll personally not look further into fixing this myself for now tho. Sorry. :/

**Comment by benyaminl** [comment] 2021-11-19 13:06
@gmkmario are you sure that you're using Dark Theme on Firefox? I mean the firefox theme? Not only by set color on the userChrome.css? Because I can reproduce IF ONLY I use system theme from Firefox with black color on userChrome like this. 

Without Dark Theme from Firefox
![image](https://user-images.githubusercontent.com/2817332/142627265-3f2ce21b-b5f4-4952-bc93-4fbfb93b4db4.png)

With Dark Theme from Firefox 
![image](https://user-images.githubusercontent.com/2817332/142627329-8beffc6d-8fcf-48e1-8327-16063c816bfb.png)

If you haven't turn on the black/dark theme on firefox, try to turn it on, and check does it works or not, if It's not then we can force using 

```css
:root {
 color: #fff !important;
}
```

as the dialog box rely on :root color 
example 
![image](https://user-images.githubusercontent.com/2817332/142627616-1506936c-a2c4-4016-b7af-41d5b0dfe938.png)

**Comment by andreasgrafen** [comment] 2021-11-19 21:58
Oh, that's a great pointer! That probably explains why I had no way to reproduce this. I didn't bother checking with systemwide Lighttheme on my machine!
Thanks you so much for this. c:

**Comment by gmkmario** [comment] 2021-12-04 23:58
I had to force the colors but it works!

**Comment by benyaminl** [comment] 2021-12-05 02:39
> I had to force the colors but it works!

You have 2 option regarding this, 1st you use your default color from your themes, that mean you must comment the overriding color part and use system color on these lines https://github.com/andreasgrafen/cascade/blob/main/userChrome.css#L39-L64, or you do what I suggest above. 

Anyway if it's solved, then you need to close this issue.

**Closed** 2021-12-10 13:41 UTC
Labels: help wanted, design
