### ISSUE TITLE
how to add the glow effect from the tabs

### ISSUE THREAD

**Issue by jbugel-lol** [andreasgrafen/cascade#111] opened 2023-12-12 20:04 UTC
so yea, I would like the glow effect of other open tabs, and dont knowhow to do that

**Comment by tunjan** [comment] 2023-12-13 12:30
I find myself with the same issue. Using Firefox 120.0.1

**Comment by tunjan** [comment] 2023-12-15 19:57
Hi! This is a duplicate of #104

**Closed** 2024-02-02 06:48 UTC
Labels: support
